export const clueLibrary = {
  leads: [
    { title: "Thermal Residue", detail: "Heat signature indicates a quantum drive went active 3 minutes before the break-in.", tags: ["Evidence"] },
    { title: "Encrypted Page", detail: "A torn journal page contains coordinates hidden under reactive ink.", tags: ["Puzzle"] },
    { title: "Anonymous Tip", detail: "Voice-altered call mentions a hand-off at Pier 19 just after sunset.", tags: ["Witness"] },
    { title: "City Cam Snapshot", detail: "Blurry image captures a figure swapping duffel bags at the monorail hub.", tags: ["Surveillance"] },
    { title: "Accelerant Sample", detail: "Chemical analysis shows the accelerant was custom-engineered to burn cold.", tags: ["Forensics"] },
    { title: "Dispatch Log", detail: "Responder log notes power fluctuations exactly when the vault alarm tripped.", tags: ["Systems"] },
    { title: "Holo-Key Fragment", detail: "A fractured holographic key glows with the signature of Axiom Industries.", tags: ["Tech"] },
    { title: "Arcade Token", detail: "Token from the Boardwalk Arcade has fresh scorch marks and residual ozone.", tags: ["Oddity"] },
    { title: "Nanite Swarm", detail: "Dormant nanites recovered from the crime scene respond to a hidden carrier wave.", tags: ["Science"] },
    { title: "Courier Route", detail: "Delivery drone was diverted mid-route, bypassing air traffic controls.", tags: ["Logistics"] },
    { title: "Submerged Drive", detail: "Black box recovered from the harbour shows tampering with the ballast AI.", tags: ["Evidence"] },
    { title: "Phase Residue", detail: "Residual phase particles match the villain’s teleport rig from prior heists.", tags: ["Tech"] },
    { title: "Atlas Transit Pass", detail: "VIP pass used minutes before the attack ties to a shell corporation.", tags: ["Finance"] },
    { title: "Sky Patrol Report", detail: "Patrol drone flagged anomalous thermal plumes above the skyline.", tags: ["Surveillance"] },
    { title: "Recovered Sat-Phone", detail: "Encrypted sat-phone cache pings a private relay in the Arctic.", tags: ["Comms"] },
    { title: "Quantum Ledger", detail: "Ledger entries show micro-deposits funnelling into the villain’s network.", tags: ["Finance"] },
    { title: "Arc Reactor Core", detail: "Miniaturised reactor core scraped along the vault wall.", tags: ["Forensics"] },
    { title: "Fractured Gauntlet", detail: "Armor gauntlet plating contains alloy unique to the villain’s suit.", tags: ["Evidence"] },
    { title: "Temporal Drift", detail: "Chronometer recorded a 4-second time skip during the operation.", tags: ["Temporal"] },
    { title: "Streetlight Archive", detail: "City streetlight sensors captured a lightwave fingerprint of an accomplice.", tags: ["Surveillance"] },
    { title: "Encrypted Badge", detail: "Security badge duplicates captain-level credentials but lacks biometrics.", tags: ["Systems"] },
    { title: "Harmonic Crystal", detail: "Crystal resonates when exposed to the villain’s anthem frequencies.", tags: ["Science"] },
    { title: "Dusting Drone", detail: "Janitorial drone log reveals unauthorized cleaning cycle near the vault.", tags: ["Logistics"] },
    { title: "Civic Ledger", detail: "City contract adjustments rerouted funds to a proxy front.", tags: ["Finance"] },
    { title: "Pheromone Lure", detail: "Air samples show tailored pheromones used to distract guard animals.", tags: ["Forensics"] },
    { title: "Spectral Echo", detail: "Spectral scanners picked up a mirage field layered over the hallway.", tags: ["Arcane"] },
    { title: "Broken Restraints", detail: "Restraint cuffs were filed open with a plasma micro-torch.", tags: ["Evidence"] },
    { title: "Evac Route Overlay", detail: "Emergency exit overlays redirected crowds away from a service lift.", tags: ["Systems"] },
    { title: "Microdrone Hull", detail: "Hull fragment from a microdrone still transmits telemetry.", tags: ["Tech"] },
    { title: "Eco Sensor Alert", detail: "Biosphere sensors flagged a rapid oxygen drop in greenhouse wing.", tags: ["Environment"] },
    { title: "Residue Lace", detail: "Residue from the scene matches polymer weaves from smugglers’ shipments.", tags: ["Forensics"] },
    { title: "Quantum Breadcrumb", detail: "Entangled particles lead toward a maintenance tunnel.", tags: ["Science"] },
    { title: "Vandalised Billboard", detail: "Billboard hijacked mid-broadcast to mask escape vectors.", tags: ["Distraction"] },
    { title: "Rail Schedule Hack", detail: "Metro AI rescheduled freight to leave a deserted platform.", tags: ["Systems"] },
    { title: "Sky Harpoon", detail: "Projectile lodged in a zeppelin hull matches villain kit.", tags: ["Evidence"] },
    { title: "Resonant Footprint", detail: "Footprint impressions vibrate at harmonics tied to grav-boots.", tags: ["Forensics"] },
    { title: "Crowdsourced Clip", detail: "Citizen footage shows a decoy team handing off a containment case.", tags: ["Witness"] },
    { title: "Collapsed Drone Swarm", detail: "Swarm AI triggered a hard reboot, leaving pathing coordinates.", tags: ["Tech"] },
    { title: "Intercepted Invoice", detail: "Invoice for exotic capacitors approved by a compromised board member.", tags: ["Finance"] },
    { title: "Runic Seal", detail: "Runic seal etched under the vault flickers with spent energy.", tags: ["Arcane"] },
    { title: "Signal Ghost", detail: "Ghost signal of an emergency beacon rerouted to an abandoned pier.", tags: ["Comms"] },
    { title: "Locksmith Chip", detail: "Chipset replicates high-security tumblers used in private vaults.", tags: ["Evidence"] },
    { title: "Hologram Drift", detail: "Security hologram drifted five degrees, creating a blind spot.", tags: ["Systems"] },
    { title: "Warehouse Ledger", detail: "Warehouse manifests list crates swapped with empty shells.", tags: ["Logistics"] },
    { title: "Meteoric Dust", detail: "Dust composition aligns with meteor fragments collected last week.", tags: ["Science"] },
    { title: "Mind-Link Trace", detail: "Psionic residue indicates a remote telepath directed the heist.", tags: ["Psychic"] },
    { title: "Jailbreak Packet", detail: "Firewall logs show a jailbreak packet piggybacked on maintenance traffic.", tags: ["Systems"] },
    { title: "Exposed Servos", detail: "Servos from the villain’s drone line left a lubricant trail.", tags: ["Evidence"] },
    { title: "Aqua Lock Override", detail: "Water treatment valves cycled unexpectedly to flood escape routes.", tags: ["Environment"] },
    { title: "Thermal Cloak Tear", detail: "Fragment of thermal cloak woven from stealth mesh recovered.", tags: ["Tech"] },
    { title: "Mag-Rail Scrape", detail: "Scrape pattern on mag-rail walkway matches stolen hover-sled.", tags: ["Forensics"] },
    { title: "Displaced Crate", detail: "Storage crate filled with ballast replaced high-value components.", tags: ["Logistics"] },
    { title: "Glyph-stamped Card", detail: "Calling card etched with a cipher matching villain fan forums.", tags: ["Culture"] },
    { title: "Emergency Beacon", detail: "Handheld beacon triggered a false evac to clear security.", tags: ["Witness"] },
    { title: "Volatile Coolant", detail: "Cooling fluid sample laced with accelerants to induce system panic.", tags: ["Forensics"] },
    { title: "Shield Fragment", detail: "Broken shield emitter retains a viral firmware signature.", tags: ["Tech"] },
    { title: "Evacuation Badge", detail: "Badge logs show a janitor evacuated twice in one minute.", tags: ["Systems"] },
    { title: "Vault Echo Map", detail: "Echolocation map reveals a hollow chamber behind the treasury.", tags: ["Evidence"] },
    { title: "Civic Sensor Ping", detail: "City sensors detected micro-seismic pulses along the escape path.", tags: ["Environment"] },
    { title: "Polarity Burn", detail: "Ceiling beams scorched with inverted polarity arcs.", tags: ["Science"] },
    { title: "Tactical Memo", detail: "Memo from a private security firm outlines identical countermeasures.", tags: ["Intel"] },
  ],
  redHerrings: [
    { title: "Gossip Column", detail: "Celebrity sighting claims the villain was across town during the incident.", tags: ["Rumour"], redHerring: true },
    { title: "Tabloid Scoop", detail: "Anonymous blog insists the heist was staged for marketing.", tags: ["Noise"], redHerring: true },
    { title: "Street Artist", detail: "Graffiti near the scene mimics the villain’s emblem but predates the attack.", tags: ["Distraction"], redHerring: true },
    { title: "Spoofed Memo", detail: "Leaked memo accuses a rival hero team with no supporting data.", tags: ["Noise"], redHerring: true },
    { title: "Tourist Photo", detail: "Vacation selfie allegedly spots the villain, but metadata is forged.", tags: ["Rumour"], redHerring: true },
    { title: "Astrology Chart", detail: "Horoscope blog predicts the heist outcome with uncanny detail.", tags: ["Pseudoscience"], redHerring: true },
    { title: "Fan Forum Thread", detail: "Fan theory connects the crime to a cancelled comic storyline.", tags: ["Distraction"], redHerring: true },
    { title: "Corporate Rumor", detail: "Office gossip blames an internal merger for missing assets.", tags: ["Noise"], redHerring: true },
    { title: "Fake Warranty", detail: "Warranty scammer offers replacement vault parts no questions asked.", tags: ["Noise"], redHerring: true },
    { title: "Old Case File", detail: "Archival footage from a decade-old heist resurfaces as proof.", tags: ["Distraction"], redHerring: true },
    { title: "Mask Replica", detail: "Cosplay mask found nearby sends analysts chasing prop fabricators.", tags: ["Rumour"], redHerring: true },
    { title: "Overheard Boast", detail: "Bar patron brags about the crime but has an airtight alibi.", tags: ["Witness"], redHerring: true },
    { title: "Anonymous Poll", detail: "Viral poll names an unrelated celebrity as mastermind.", tags: ["Noise"], redHerring: true },
    { title: "Satirical Article", detail: "Satire site jokes about the crime, sparking misdirection.", tags: ["Distraction"], redHerring: true },
    { title: "Expired Keycard", detail: "Keycard found in alley expired months ago.", tags: ["Evidence"], redHerring: true },
    { title: "Prototype Invoice", detail: "Prototype gear invoice is actually for a movie production.", tags: ["Noise"], redHerring: true },
    { title: "Ghost Story", detail: "Urban legend email claims a phantom repeated the heist.", tags: ["Rumour"], redHerring: true },
    { title: "Street Performance", detail: "Illusionist troupe took over the plaza minutes after the crime.", tags: ["Distraction"], redHerring: true },
    { title: "Anonymous Confession", detail: "Online confession traced to a prankster chasing clout.", tags: ["Noise"], redHerring: true },
    { title: "Fake Recall Notice", detail: "Recall notice for the vault brand is entirely fabricated.", tags: ["Noise"], redHerring: true },
  ],
  cases: [
    { name: "Operation Glasshouse", summary: "Containment research compromised after a stealth insertion at the bio-dome.", focus: "Biohazard Theft" },
    { name: "Midnight Confluence", summary: "A telepathic cabal synchronized citywide diversions to mask the vault breach.", focus: "Psychic Coordination" },
    { name: "Pierce Street Incident", summary: "Subterranean smugglers rerouted cargo tunnels toward the capital archives.", focus: "Tunnel Infiltration" },
    { name: "Ghostline Uplink", summary: "An abandoned satellite uplink sprung to life moments before the alarms tripped.", focus: "Signal Hijack" },
    { name: "Aurora Relay Collapse", summary: "Energy relays blacked out during the heist, hinting at inside sabotage.", focus: "Power Grid Disruption" },
    { name: "Blue Sun Breach", summary: "Solar research lab flagged missing isotopes after a staged fire drill.", focus: "Energy Theft" },
    { name: "Crimson Corridor", summary: "Security sweeps found micro charges planted along the art museum wing.", focus: "Explosive Diversion" },
    { name: "Neptune Echo", summary: "Underwater domes reported tremors syncing with the bank incursion.", focus: "Aquatic Escape" },
    { name: "Vanguard Skystorm", summary: "Private defense platforms rotated away seconds before the attack.", focus: "Orbital Manipulation" },
    { name: "Clocktower Riddle", summary: "Temporal locks flickered as if the entire hour was rewritten.", focus: "Chronal Sabotage" },
  ],
};

export const cipherLibrary = [
  { id: "alphanumeric", name: "Alpha-Numeric Cipher", symbols: "ABCDEFGHJKLMNPQRSTUVWXYZ23456789", hint: "Console cycling through standard alphanumerics. Watch for letters that linger.", defaultLength: 5 },
  { id: "glyph", name: "Aether Glyph Cipher", symbols: "ΔΛΩΨΦΞΣΓΘ", hint: "Ancient glyph bank detected. Harmonise the sequence to stabilise the output.", defaultLength: 4 },
  { id: "emoji", name: "Emoji Substitution Cipher", symbols: ["⚡", "🔥", "💎", "🛰️", "🧬", "🛡️", "🔮", "🧠", "🌀"], hint: "Console projecting emotive sigils—each flare betrays a real rune.", defaultLength: 4 },
  { id: "binary-core", name: "Binary Core Cipher", symbols: "01", hint: "System fallback to binary pulses. Expect tight sequences.", defaultLength: 6 },
  { id: "resonance", name: "Resonance Prism Cipher", symbols: "PRISMΔ◇◆⬡⬢⬣⬢", hint: "Prismatic symbols indicate a resonance cascade. Match the harmonics.", defaultLength: 5 },
  { id: "stellar", name: "Stellar Navigation Cipher", symbols: "✶✷✸✹✺✻✼✽✾✿", hint: "Starfield glyphs rotating in orbital patterns. Align the constellation order.", defaultLength: 5 },
  { id: "runic-shift", name: "Runic Shift Cipher", symbols: "ᚠᚢᚦᚨᚱᚲᚷᚹᛒᛖ", hint: "Nordic runes flicker as the console cycles. Watch for glowing etchings.", defaultLength: 5 },
  { id: "quantum-spin", name: "Quantum Spin Cipher", symbols: "↑↓↱↲↺↻⇅⇄", hint: "Spin-state indicators flash between axis alignments. Track the reversals.", defaultLength: 6 },
  { id: "hexadecimal", name: "Hexadecimal Cipher", symbols: "0123456789ABCDEF", hint: "Diagnostic hex grid online. Expect repeating pairs to appear.", defaultLength: 6 },
  { id: "celestial", name: "Celestial Chant Cipher", symbols: "☉☾☿♀♁♂♃♄♅♆♇", hint: "Celestial icons hum with tonal cues. The correct order resonates softly.", defaultLength: 5 },
  { id: "bio-signal", name: "Bio-Signal Cipher", symbols: "AUGCΨΣΛΩ", hint: "Bio-digital codex engaged. Prioritise stable nucleotide pairs.", defaultLength: 5 },
  { id: "mythic-crest", name: "Mythic Crest Cipher", symbols: "♜♞♝♛♚♝♞♜", hint: "Strategic crest icons align like a chess formation.", defaultLength: 6 },
  { id: "nova-flare", name: "Nova Flare Cipher", symbols: "☄︎✹✺✻✼✽", hint: "Solar flares erupt in rhythmic bursts. Match the flare cadence.", defaultLength: 4 },
  { id: "pulsewave", name: "Pulsewave Cipher", symbols: "▁▂▃▄▅▆▇█", hint: "Amplitude bars rise and fall. The highest plateaus indicate true symbols.", defaultLength: 5 },
  { id: "harmonic", name: "Harmonic Lattice Cipher", symbols: "△▽◁▷◆◇⬗⬘", hint: "Geometric lattice rotates with alternating pitches. Listen for the even beat.", defaultLength: 5 },
  { id: "cipher-nine", name: "Cipher Nine Protocol", symbols: "ACEGIKMOQSUWY", hint: "Only odd-lettered glyphs remain. Pay attention to spacing.", defaultLength: 6 },
  { id: "ember-script", name: "Ember Script Cipher", symbols: ["🔥", "💥", "⚙️", "💡", "🧨", "⚡", "🔩"], hint: "Ember script ignites sporadically. True symbols leave afterimages.", defaultLength: 5 },
  { id: "frost-byte", name: "Frost Byte Cipher", symbols: "❄︎✶✻✼❆✺✾", hint: "Cryonic glyphs crystallise slowly. The ones that linger are authentic.", defaultLength: 4 },
  { id: "radial-loop", name: "Radial Loop Cipher", symbols: "↻↺⟲⟳⤾⤿", hint: "Looped arrows accelerate with each tick. The decelerations spell the key.", defaultLength: 5 },
  { id: "spectral", name: "Spectral Echo Cipher", symbols: "αβγδεζηθικλ", hint: "Spectral field broadcasts classic Greek characters. Echoing ones are valid.", defaultLength: 6 },
  { id: "aeon-script", name: "Aeon Script Cipher", symbols: "᛫᛬᛭ᛮᛯᛰ", hint: "Ancient aeon script shimmers in pairs. Match mirrored marks.", defaultLength: 4 },
  { id: "thunderhead", name: "Thunderhead Cipher", symbols: ["🌩️", "⚡", "🌧️", "☁️", "🌪️", "🌩️"], hint: "Stormfront icons flicker in charged intervals. The brightest strikes repeat.", defaultLength: 5 },
  { id: "digital-silk", name: "Digital Silk Cipher", symbols: "絲糸纟纨纩纫纭纮", hint: "Nanoweave characters scroll elegantly—watch for doubled threads.", defaultLength: 5 },
  { id: "core-logic", name: "Core Logic Cipher", symbols: "∧∨⊕⊗⊙⊚⊛", hint: "Logical operators align in truth tables. Balanced pairs stay lit.", defaultLength: 5 },
  { id: "solar-grid", name: "Solar Grid Cipher", symbols: "ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩ", hint: "Roman numerals glow with solar intensity. The repeating numeral is key.", defaultLength: 5 },
  { id: "nebula", name: "Nebula Cipher", symbols: ["🪐", "🌌", "⭐", "☄️", "🛰️", "🌠", "🌙"], hint: "Nebula icons swirl. Those drawn into the centre ring remain true.", defaultLength: 5 },
  { id: "dynamo", name: "Dynamo Cipher", symbols: "⚙︎⚙︎⚙︎⚙︎⚙︎⚙︎", hint: "Mechanical teeth clatter. Listen for the double-click cadence.", defaultLength: 4 },
  { id: "psionic", name: "Psionic Cipher", symbols: "ΨΨΨΩΩΩΛΛΛ", hint: "Psionic pulses echo in threes. The third vibration is reliable.", defaultLength: 6 },
  { id: "aurora", name: "Aurora Cipher", symbols: "🟦🟩🟨🟧🟥🟪", hint: "Color bands drift like auroras. The ones that arc upward are correct.", defaultLength: 5 },
  { id: "meridian", name: "Meridian Cipher", symbols: "NSEW↖↘↗↙", hint: "Compass bearings snap to meridian lines. Track consecutive bearings.", defaultLength: 5 },
  { id: "draconic", name: "Draconic Cipher", symbols: "龍炎牙爪翼心魂", hint: "Draconic script snarls with ember trails. The letters with ember tails are real.", defaultLength: 5 },
  { id: "ion-script", name: "Ion Script Cipher", symbols: "+-±∓⊕⊖", hint: "Ion charges flip rapidly. Net-positive pulses stay highlighted.", defaultLength: 5 },
  { id: "horizon", name: "Horizon Cipher", symbols: "—‖╱╲╳╱╲", hint: "Linear glyphs slide like horizon markers. The intersecting lines reveal truth.", defaultLength: 6 },
  { id: "circuit-web", name: "Circuit Web Cipher", symbols: "⌁⌂⌄⌁⌂⌄⌁⌂", hint: "Circuit traces glow sequentially. Repeat traces form the passcode.", defaultLength: 5 },
  { id: "lumen", name: "Lumen Cipher", symbols: "✧✦✥✤✣✢", hint: "Lightbursts brighten to full glare when they match the true key.", defaultLength: 4 },
  { id: "fractal", name: "Fractal Cipher", symbols: "⚛︎☢︎☣︎☤︎☯︎", hint: "Fractal hazard symbols branch recursively. The nested ones remain.", defaultLength: 5 },
  { id: "terra", name: "Terra Cipher", symbols: ["🌿", "🍃", "🍂", "🌾", "🍁", "🌱"], hint: "Botanical runes shimmer when they complete a growth cycle.", defaultLength: 5 },
  { id: "violet-shift", name: "Violet Shift Cipher", symbols: "VIOLET", hint: "Spectrum narrows to violet bands. The brightest letter is authentic.", defaultLength: 6 },
  { id: "sigma-rho", name: "Sigma Rho Cipher", symbols: "ΣΡΤΛΜΝΞΟ", hint: "Greek sigma-rho pairs align. Echoed consonants are valid.", defaultLength: 6 },
  { id: "cinder", name: "Cinder Cipher", symbols: "⟁⟡⟠⟢⟣⟤", hint: "Ashen sigils flare red when correct. Misfires sputter quickly.", defaultLength: 5 },
  { id: "tidal-lock", name: "Tidal Lock Cipher", symbols: "🌊🌬️🌙☀️🌊🌬️", hint: "Tidal icons rise and ebb. The rising crest marks the authentic glyph.", defaultLength: 5 },
  { id: "relay", name: "Relay Cipher", symbols: "▸▹►▻◅◂◄◃", hint: "Directional indicators hop like data packets. The ones that repeat twice are true.", defaultLength: 5 },
  { id: "fusion", name: "Fusion Core Cipher", symbols: "⚛️🔆🧪🔬🧲💡", hint: "Fusion diagnostics cycle through scientific icons. Sparks reveal the match.", defaultLength: 5 },
  { id: "tessellation", name: "Tessellation Cipher", symbols: "⬣⬢⬡⬢⬣⬢", hint: "Honeycomb tessellations oscillate. The ones that lock flush are correct.", defaultLength: 5 },
  { id: "chrono", name: "Chrono Cipher", symbols: "ⅠⅡⅢⅣⅤⅥ", hint: "Clock ticks emphasise roman numerals. Listen for skipped beats.", defaultLength: 4 },
  { id: "golem", name: "Golem Cipher", symbols: "אבתגשכחל", hint: "Arcane golem runes grind slowly. The heavy glyphs endure.", defaultLength: 5 },
  { id: "singularity", name: "Singularity Cipher", symbols: ["⚫", "🕳️", "⚪", "🔵", "⚫", "🕳️"], hint: "Event horizon icons distort. Those pulled inward anchor the passcode.", defaultLength: 5 },
  { id: "embergrid", name: "Embergrid Cipher", symbols: "ABCDE", hint: "Classic training cipher with ember-lit letters. Repeat glows mark truth.", defaultLength: 5 },
  { id: "veil", name: "Veil Cipher", symbols: "⌿⌄⌁⌂⌃⌅", hint: "Veil script flickers between planes. Stable glyphs refuse to blur.", defaultLength: 5 },
  { id: "auric", name: "Auric Cipher", symbols: "ϞϟϠϡϢϣ", hint: "Auric lightning marks the correct numerals. Count the double bolts.", defaultLength: 5 },
  { id: "sentinel", name: "Sentinel Cipher", symbols: ["🛡️", "⚔️", "🏛️", "🗝️", "🛡️", "⚔️"], hint: "Sentinel icons rotate in defense pairs. Lock in the repeating crest.", defaultLength: 5 },
  { id: "emberline", name: "Emberline Cipher", symbols: "ABCDEFG", hint: "Training dataset for junior agents. Flickering letters always start the code.", defaultLength: 5 },
];

export const lockdownSubsystemLibrary = [
  { id: "reactor", label: "Reactor Stabiliser", description: "Keeps the antimatter core from slipping out of sync.", actionLabel: "Pulse coolant", baseline: 60, volatility: 1.1, recovery: 18, boost: 14 },
  { id: "security", label: "Security Countermeasures", description: "Balances drones, turrets, and shield nodes.", actionLabel: "Recalibrate turrets", baseline: 55, volatility: 1, recovery: 18, boost: 12 },
  { id: "evac", label: "Civilian Evacuation", description: "Guides evac pods toward the safe zone.", actionLabel: "Redirect evac pods", baseline: 58, volatility: 0.95, recovery: 17, boost: 12 },
  { id: "cryostasis", label: "Cryostasis Vault", description: "Prevents the cryo-vault from thawing critical samples.", actionLabel: "Reprime coolant", baseline: 62, volatility: 1.05, recovery: 16, boost: 12 },
  { id: "shield-array", label: "Perimeter Shield Array", description: "Maintains the phased barrier around the complex.", actionLabel: "Reinforce barrier", baseline: 57, volatility: 1.2, recovery: 19, boost: 13 },
  { id: "medbay", label: "Medbay Autodocs", description: "Ensures autodoc triage remains online.", actionLabel: "Cycle triage bots", baseline: 59, volatility: 0.9, recovery: 16, boost: 11 },
  { id: "hangar", label: "Strike Hangar", description: "Keeps launch rails and munitions safe for scramble.", actionLabel: "Purge hangar vents", baseline: 63, volatility: 1.15, recovery: 18, boost: 14 },
  { id: "orbital-relay", label: "Orbital Relay Uplink", description: "Handles comms with orbiting defense platforms.", actionLabel: "Resync uplink", baseline: 54, volatility: 1.05, recovery: 17, boost: 12 },
  { id: "hydroponics", label: "Hydroponics Ecosystem", description: "Prevents greenhouse collapse that could release toxins.", actionLabel: "Vent nutrient mist", baseline: 61, volatility: 0.85, recovery: 15, boost: 11 },
  { id: "gravity-well", label: "Gravity Well Dampeners", description: "Stabilises artificial gravity under surge stress.", actionLabel: "Realign dampeners", baseline: 56, volatility: 1.25, recovery: 20, boost: 14 },
  { id: "vault-locks", label: "Vault Locks", description: "Keeps the vault seals magnetised despite overrides.", actionLabel: "Reset lock coils", baseline: 58, volatility: 1.1, recovery: 18, boost: 12 },
  { id: "nanite-fabricator", label: "Nanite Fabricator", description: "Stops rogue nanites from self-replicating.", actionLabel: "Purge build queue", baseline: 55, volatility: 1.3, recovery: 19, boost: 13 },
  { id: "quantum-archive", label: "Quantum Archive", description: "Locks down entangled research drives.", actionLabel: "Re-entangle nodes", baseline: 60, volatility: 1.05, recovery: 17, boost: 12 },
  { id: "telemetry", label: "Telemetry Grid", description: "Ensures battlefield data uplinks stay clean.", actionLabel: "Flush telemetry", baseline: 52, volatility: 0.9, recovery: 15, boost: 11 },
  { id: "psi-shield", label: "Psi Shield Projectors", description: "Prevents psychic interference from breaching HQ.", actionLabel: "Stabilise field", baseline: 64, volatility: 1.2, recovery: 19, boost: 13 },
  { id: "drone-foundry", label: "Drone Foundry", description: "Keeps production lines from overclocking drones.", actionLabel: "Throttle fabricators", baseline: 59, volatility: 1.1, recovery: 18, boost: 12 },
  { id: "weather-dome", label: "Weather Control Dome", description: "Suppresses storm walls generated by the assault.", actionLabel: "Balance jetstream", baseline: 57, volatility: 1.15, recovery: 18, boost: 12 },
  { id: "dimensional-lock", label: "Dimensional Lock", description: "Prevents interdimensional breaches.", actionLabel: "Seal rifts", baseline: 62, volatility: 1.3, recovery: 20, boost: 15 },
  { id: "omega-forge", label: "Omega Forge", description: "Stops the forge from overheating and detonating stockpiles.", actionLabel: "Bleed excess heat", baseline: 55, volatility: 1.25, recovery: 19, boost: 14 },
  { id: "core-vault", label: "Core Vault Containment", description: "Maintains magnet containment for the core vault.", actionLabel: "Reinforce seals", baseline: 63, volatility: 1.35, recovery: 20, boost: 14 },
  { id: "arcology", label: "Arcology Support Struts", description: "Keeps megastructure columns from collapsing under stress.", actionLabel: "Re-lock struts", baseline: 58, volatility: 1.15, recovery: 18, boost: 13 },
  { id: "signal-jammer", label: "Signal Jammer Array", description: "Shields HQ from enemy comms infiltration.", actionLabel: "Rephase jammers", baseline: 54, volatility: 0.95, recovery: 16, boost: 11 },
  { id: "containment", label: "Containment Pods", description: "Stops containment pods from failing open.", actionLabel: "Clamp pods", baseline: 60, volatility: 1.05, recovery: 17, boost: 12 },
  { id: "bastion-walls", label: "Bastion Walls", description: "Maintains kinetic barriers around perimeter walls.", actionLabel: "Fortify ramparts", baseline: 57, volatility: 1.15, recovery: 18, boost: 12 },
  { id: "relay-beacons", label: "Relay Beacon Network", description: "Guides reinforcements via beacon coordinates.", actionLabel: "Recalibrate beacons", baseline: 53, volatility: 0.9, recovery: 16, boost: 11 },
  { id: "arc-light", label: "Arc-Light Conduits", description: "Keeps lightning conduits from overloading.", actionLabel: "Discharge conduits", baseline: 56, volatility: 1.2, recovery: 18, boost: 12 },
  { id: "shadow-net", label: "Shadow Net", description: "Disrupts stealth incursions around the base.", actionLabel: "Ping shadow net", baseline: 55, volatility: 1.1, recovery: 18, boost: 12 },
  { id: "bio-filters", label: "Bio-Filters", description: "Filters toxins released by saboteurs.", actionLabel: "Cycle filters", baseline: 59, volatility: 0.9, recovery: 16, boost: 11 },
  { id: "skyway", label: "Skyway Traffic Control", description: "Manages aerial lanes for evac craft.", actionLabel: "Reroute sky lanes", baseline: 52, volatility: 1, recovery: 17, boost: 12 },
  { id: "vault-drone", label: "Vault Drone Patrol", description: "Keeps patrol drones from deserting the perimeter.", actionLabel: "Reassign patrols", baseline: 58, volatility: 1.05, recovery: 17, boost: 12 },
  { id: "quantum-anchor", label: "Quantum Anchors", description: "Secures reality anchors against phase shifts.", actionLabel: "Lock anchors", baseline: 62, volatility: 1.3, recovery: 20, boost: 15 },
  { id: "ember-sprinklers", label: "Ember Sprinklers", description: "Deploys flame-retardant nanomist.", actionLabel: "Purge pyro bots", baseline: 55, volatility: 0.95, recovery: 16, boost: 11 },
  { id: "psionic-reserve", label: "Psionic Reserve", description: "Protects the empathic ward from overload.", actionLabel: "Meditative pulse", baseline: 63, volatility: 1.2, recovery: 19, boost: 13 },
  { id: "holo-decoys", label: "Holo-Decoy Network", description: "Keeps decoys aligned to confuse intruders.", actionLabel: "Re-sync projectors", baseline: 57, volatility: 1.05, recovery: 17, boost: 12 },
  { id: "triage-network", label: "Triage Network", description: "Routes med-bots efficiently through the compound.", actionLabel: "Optimise routes", baseline: 58, volatility: 0.92, recovery: 16, boost: 11 },
  { id: "storm-shield", label: "Storm Shield", description: "Buffers against the electrical supercell outside.", actionLabel: "Ground capacitors", baseline: 60, volatility: 1.18, recovery: 18, boost: 12 },
  { id: "entropy-sink", label: "Entropy Sink", description: "Keeps the lab’s entropy sink from reversing.", actionLabel: "Vent entropy sink", baseline: 61, volatility: 1.22, recovery: 19, boost: 13 },
  { id: "supply-chain", label: "Supply Chain Bay", description: "Ensures logistics drones keep vital supplies flowing.", actionLabel: "Boost supply drones", baseline: 56, volatility: 0.9, recovery: 16, boost: 11 },
  { id: "fusion-ring", label: "Fusion Ring", description: "Maintains stability in the fusion test chamber.", actionLabel: "Re-tune injectors", baseline: 59, volatility: 1.25, recovery: 19, boost: 13 },
  { id: "guardian-ai", label: "Guardian AI", description: "Prevents the security AI from isolating the wrong sectors.", actionLabel: "Reboot guardian", baseline: 54, volatility: 1.05, recovery: 17, boost: 12 },
  { id: "siren-grid", label: "Siren Grid", description: "Keeps evacuation sirens sequenced correctly.", actionLabel: "Resequence sirens", baseline: 55, volatility: 0.88, recovery: 15, boost: 11 },
  { id: "terraformer", label: "Terraformer Control", description: "Stops the terraformer from rewriting the campus layout.", actionLabel: "Lock terrain maps", baseline: 60, volatility: 1.28, recovery: 19, boost: 13 },
  { id: "atlas-pylons", label: "Atlas Pylons", description: "Supports the anti-grav pylons underpinning HQ.", actionLabel: "Stiffen pylons", baseline: 58, volatility: 1.18, recovery: 18, boost: 12 },
  { id: "wraith-scanners", label: "Wraith Scanners", description: "Detects phase-shifted infiltrators.", actionLabel: "Sweep for wraiths", baseline: 57, volatility: 1.1, recovery: 18, boost: 12 },
  { id: "echo-vault", label: "Echo Vault", description: "Stores psychic echoes from captured villains.", actionLabel: "Scrub echo vault", baseline: 59, volatility: 1.12, recovery: 18, boost: 12 },
  { id: "ion-thrusters", label: "Ion Thruster Bay", description: "Maintains orbital shuttle readiness.", actionLabel: "Flush thrusters", baseline: 56, volatility: 1.2, recovery: 18, boost: 12 },
  { id: "null-field", label: "Null Field Emitters", description: "Prevents powered gear from overloading inside HQ.", actionLabel: "Stabilise null field", baseline: 61, volatility: 1.25, recovery: 19, boost: 13 },
  { id: "chrono-vault", label: "Chrono Vault", description: "Locks down time-sensitive artifacts.", actionLabel: "Rewind feedback", baseline: 62, volatility: 1.3, recovery: 20, boost: 14 },
  { id: "deep-archives", label: "Deep Archives", description: "Protects the data stacks from purge cycles.", actionLabel: "Shunt purge cycle", baseline: 55, volatility: 1.05, recovery: 17, boost: 12 },
  { id: "portal-gate", label: "Portal Gate", description: "Ensures the gate remains aligned to safe coordinates.", actionLabel: "Re-index gate", baseline: 60, volatility: 1.27, recovery: 19, boost: 13 },
  { id: "aerial-wardens", label: "Aerial Wardens", description: "Keeps aerial wardens from going rogue under signal loss.", actionLabel: "Stabilise wardens", baseline: 57, volatility: 1.1, recovery: 18, boost: 12 },
  { id: "omega-sirens", label: "Omega Sirens", description: "Prevents panic by modulating the crisis siren tone.", actionLabel: "Tune omega sirens", baseline: 53, volatility: 0.9, recovery: 15, boost: 11 },
];

export const powerSurgeEventLibrary = [
  { id: "ion-backdraft", title: "Ion Backdraft", ticker: "Ion backdraft rattles the coils.", description: "Residual charge surges backward through the array, nudging output upward.", volatility: 1.2, bias: 1.5, duration: 3, ventModifier: 1.1, boostModifier: 0.9 },
  { id: "coolant-drop", title: "Coolant Drop", ticker: "Coolant pressure dips dangerously.", description: "A coolant leak bleeds heat away causing a steady loss.", volatility: 0.9, bias: -1.8, duration: 4, ventModifier: 0.8, boostModifier: 1.05 },
  { id: "harmonic-spike", title: "Harmonic Spike", ticker: "Harmonic oscillations spike.", description: "Resonant frequencies build causing erratic swings.", volatility: 1.35, bias: 0.2, duration: 3, ventModifier: 1, boostModifier: 1 },
  { id: "phase-shift", title: "Phase Shift Echo", ticker: "Phase shift echo ripples the chamber.", description: "Reality hiccup drags the meter upward unpredictably.", volatility: 1.4, bias: 2.2, duration: 2, ventModifier: 1.2, boostModifier: 0.85 },
  { id: "drain-tap", title: "Drain Tap", ticker: "Hidden siphon pulls at the core.", description: "A covert drain pulls energy off the top, lowering the gauge.", volatility: 1, bias: -2, duration: 3, ventModifier: 0.75, boostModifier: 1.1 },
  { id: "feedback-loop", title: "Feedback Loop", ticker: "Feedback loop detected.", description: "Control loop misfires causing wild oscillations.", volatility: 1.5, bias: 0.5, duration: 3, ventModifier: 1.05, boostModifier: 1.05 },
  { id: "overclock", title: "Emergency Overclock", ticker: "Failsafe engages emergency overclock.", description: "Backup processors kick in pushing output sky-high.", volatility: 1.25, bias: 2.5, duration: 2, ventModifier: 1.15, boostModifier: 0.9 },
  { id: "vent-pulse", title: "Vent Pulse", ticker: "Auto-vent pulse flushes plasma.", description: "Automated vent keeps energy manageable if you capitalise quickly.", volatility: 0.95, bias: -1, duration: 3, ventModifier: 1.3, boostModifier: 0.8 },
  { id: "capacitor-lag", title: "Capacitor Lag", ticker: "Capacitor lag detected.", description: "Aging capacitors fail to respond leading to slow drift downward.", volatility: 0.85, bias: -1.2, duration: 4, ventModifier: 0.7, boostModifier: 1.1 },
  { id: "surge-inverter", title: "Surge Inverter", ticker: "Surge inverter misaligns.", description: "Inverter flips polarity and spikes energy erratically.", volatility: 1.45, bias: 1.5, duration: 3, ventModifier: 1.2, boostModifier: 0.95 },
  { id: "tectonic-rattle", title: "Tectonic Rattle", ticker: "Micro tremors shake the housing.", description: "Vibrations jar the regulator causing small dips.", volatility: 0.9, bias: -0.8, duration: 3, ventModifier: 0.9, boostModifier: 1 },
  { id: "signal-bleed", title: "Signal Bleed", ticker: "Signal bleed corrupts telemetry.", description: "Leaked control signals push random fluctuations.", volatility: 1.1, bias: 0.6, duration: 3, ventModifier: 1.05, boostModifier: 1.05 },
  { id: "arc-flare", title: "Arc Flare", ticker: "Containment arcs crackle.", description: "Containment cage throws sparks and lifts the output floor.", volatility: 1.25, bias: 1.8, duration: 2, ventModifier: 1.1, boostModifier: 0.95 },
  { id: "injector-misfire", title: "Injector Misfire", ticker: "Fuel injector misfires.", description: "One injector sputters, forcing a sudden drop.", volatility: 1.05, bias: -2.1, duration: 3, ventModifier: 0.8, boostModifier: 1.1 },
  { id: "coolant-surge", title: "Coolant Surge", ticker: "Coolant surge chills the core.", description: "Coolant flood dampens energy but risks freezing control lines.", volatility: 0.8, bias: -1.5, duration: 4, ventModifier: 0.85, boostModifier: 1.1 },
  { id: "gravitational-swell", title: "Gravitational Swell", ticker: "Gravity swell warps the chamber.", description: "Localized gravity distortion drags readings high.", volatility: 1.3, bias: 1.9, duration: 2, ventModifier: 1.15, boostModifier: 0.9 },
  { id: "echo-resonance", title: "Echo Resonance", ticker: "Echo resonance hum builds.", description: "Acoustic feedback rolls through the housing causing jitter.", volatility: 1.2, bias: 0.4, duration: 3, ventModifier: 1, boostModifier: 1 },
  { id: "nullwave", title: "Nullwave Dip", ticker: "Nullwave pocket suppresses output.", description: "Nullwave interference temporarily drains the core.", volatility: 0.95, bias: -2.3, duration: 2, ventModifier: 0.75, boostModifier: 1.2 },
  { id: "plasma-drizzle", title: "Plasma Drizzle", ticker: "Loose plasma rains across conduits.", description: "Plasma droplets rekindle output with noisy surges.", volatility: 1.3, bias: 1.6, duration: 3, ventModifier: 1.1, boostModifier: 0.95 },
  { id: "solar-flare", title: "Solar Flare Echo", ticker: "Solar flare echo from shields.", description: "Solar shielding reflects energy spikes into the generator.", volatility: 1.4, bias: 2.4, duration: 2, ventModifier: 1.2, boostModifier: 0.85 },
  { id: "data-flood", title: "Diagnostic Flood", ticker: "Diagnostics flood the control bus.", description: "Excess telemetry slows regulation letting energy wander.", volatility: 1.1, bias: 0.3, duration: 4, ventModifier: 1, boostModifier: 1 },
  { id: "dampener-failure", title: "Dampener Failure", ticker: "A dampener goes dark.", description: "One stabiliser shuts down causing rising spikes.", volatility: 1.35, bias: 2, duration: 3, ventModifier: 1.15, boostModifier: 0.9 },
  { id: "shield-cascade", title: "Shield Cascade", ticker: "Shield cascade drags the core.", description: "Perimeter shields borrow power pulling the gauge down.", volatility: 1, bias: -1.7, duration: 3, ventModifier: 0.85, boostModifier: 1.05 },
  { id: "thermal-slip", title: "Thermal Slip", ticker: "Heat exchangers slip out of sync.", description: "Heat exchangers fall behind letting output climb.", volatility: 1.15, bias: 1.1, duration: 3, ventModifier: 1.05, boostModifier: 0.95 },
  { id: "ionic-hum", title: "Ionic Hum", ticker: "Ionic hum vibrates panels.", description: "Static build-up adds gentle upward drift.", volatility: 1, bias: 0.8, duration: 4, ventModifier: 1, boostModifier: 0.95 },
  { id: "coolant-freeze", title: "Coolant Freeze", ticker: "Coolant edges toward freezing.", description: "Lines start to frost causing rapid downturns.", volatility: 0.85, bias: -2.5, duration: 2, ventModifier: 0.7, boostModifier: 1.15 },
  { id: "reactor-knock", title: "Reactor Knock", ticker: "Reactor knock reverberates.", description: "Rhythmic thumps jolt the meter high each beat.", volatility: 1.3, bias: 1.7, duration: 3, ventModifier: 1.1, boostModifier: 0.9 },
  { id: "vent-jam", title: "Vent Jam", ticker: "Vent shutters jam closed.", description: "Ventilation stalls and energy spikes.", volatility: 1.25, bias: 2.1, duration: 2, ventModifier: 1.3, boostModifier: 0.85 },
  { id: "static-haze", title: "Static Haze", ticker: "Static haze clouds readings.", description: "Sensor haze adds unpredictable wobble.", volatility: 1.15, bias: 0.2, duration: 3, ventModifier: 1, boostModifier: 1 },
  { id: "rotor-stall", title: "Rotor Stall", ticker: "Turbine rotor stalls.", description: "One rotor stalls slashing output until it recovers.", volatility: 0.9, bias: -2.2, duration: 2, ventModifier: 0.8, boostModifier: 1.2 },
  { id: "phase-hum", title: "Phase Hum", ticker: "Phase hum destabilises coils.", description: "Phase noise tugs energy upward then down.", volatility: 1.2, bias: 0.5, duration: 3, ventModifier: 1.05, boostModifier: 0.95 },
  { id: "chrono-wobble", title: "Chrono Wobble", ticker: "Chrono wobble desyncs timers.", description: "Temporal slip creates delayed corrections pushing overshoots.", volatility: 1.3, bias: 1.2, duration: 3, ventModifier: 1.1, boostModifier: 0.95 },
  { id: "exhaust-boom", title: "Exhaust Boom", ticker: "Exhaust boom reverbs through conduits.", description: "Backwash from exhaust flares spikes the meter.", volatility: 1.2, bias: 1.4, duration: 2, ventModifier: 1.05, boostModifier: 0.9 },
  { id: "microfracture", title: "Microfracture", ticker: "Microfracture leaks energy.", description: "Hairline crack bleeds off output slowly.", volatility: 0.9, bias: -1.1, duration: 4, ventModifier: 0.8, boostModifier: 1.05 },
  { id: "aux-boost", title: "Auxiliary Boost", ticker: "Aux systems feed power back.", description: "Auxiliary grid dumps reserves, raising the baseline.", volatility: 1.05, bias: 1.6, duration: 3, ventModifier: 1.1, boostModifier: 0.95 },
  { id: "aurora-twist", title: "Aurora Twist", ticker: "Aurora twist refracts energies.", description: "Magnetic aurora effect sways the gauge unpredictably.", volatility: 1.25, bias: 0.9, duration: 3, ventModifier: 1.05, boostModifier: 0.95 },
  { id: "arcground", title: "Arc Grounding", ticker: "Grounding rods spark.", description: "Grounding rods flare absorbing energy dips.", volatility: 1, bias: -1.4, duration: 3, ventModifier: 0.9, boostModifier: 1.1 },
  { id: "flux-spiral", title: "Flux Spiral", ticker: "Flux spiral forms in the core.", description: "Flux spiral accelerates the waveform to volatile peaks.", volatility: 1.4, bias: 1.9, duration: 2, ventModifier: 1.2, boostModifier: 0.9 },
  { id: "resonant-dip", title: "Resonant Dip", ticker: "Resonant dip drags the signal.", description: "Resonant cavity drains energy briefly.", volatility: 0.95, bias: -1.6, duration: 3, ventModifier: 0.85, boostModifier: 1.05 },
  { id: "polar-shift", title: "Polar Shift", ticker: "Polarities wobble.", description: "Magnetic poles skew causing alternating surges.", volatility: 1.3, bias: 1, duration: 3, ventModifier: 1.1, boostModifier: 0.95 },
  { id: "cascade-feedback", title: "Cascade Feedback", ticker: "Cascade feedback climbs fast.", description: "Layered feedback loops send the meter screaming upward.", volatility: 1.5, bias: 2.7, duration: 2, ventModifier: 1.2, boostModifier: 0.85 },
  { id: "ripple-flash", title: "Ripple Flash", ticker: "Ripple flash pulses outward.", description: "Wavefront ripples push quick jolts both ways.", volatility: 1.25, bias: 0.4, duration: 3, ventModifier: 1.05, boostModifier: 0.95 },
  { id: "shard-rain", title: "Shard Rain", ticker: "Crystallised shards rain across the core.", description: "Shards scrape energy away but create burst rebounds.", volatility: 1.1, bias: -0.9, duration: 3, ventModifier: 0.9, boostModifier: 1.05 },
  { id: "quantum-pop", title: "Quantum Pop", ticker: "Quantum pop destabilises readings.", description: "Quantum bubbles burst forcing sudden leaps.", volatility: 1.35, bias: 1.8, duration: 2, ventModifier: 1.15, boostModifier: 0.9 },
  { id: "psi-thrum", title: "Psi Thrum", ticker: "Psi thrum warps instrumentation.", description: "Psychic resonance alters modulation creating wobble.", volatility: 1.15, bias: 0.7, duration: 3, ventModifier: 1, boostModifier: 1 },
  { id: "undersea-drift", title: "Undersea Drift", ticker: "Moisture leak mimics undersea pressure.", description: "Heavy moisture drags output downward slowly.", volatility: 0.85, bias: -1.3, duration: 4, ventModifier: 0.8, boostModifier: 1.05 },
  { id: "cryo-bloom", title: "Cryo Bloom", ticker: "Cryo bloom chills conduits.", description: "Flash freeze damps energy but rebounds if unchecked.", volatility: 1, bias: -1.8, duration: 3, ventModifier: 0.75, boostModifier: 1.1 },
  { id: "drone-hum", title: "Drone Hum", ticker: "Maintenance drones add resonance.", description: "Drone harmonics give small steady bumps.", volatility: 0.95, bias: 0.6, duration: 4, ventModifier: 1, boostModifier: 0.95 },
  { id: "entropy-creep", title: "Entropy Creep", ticker: "Entropy creep gnaws at the baseline.", description: "Entropy sink leaks causing gradual decay.", volatility: 0.9, bias: -1.4, duration: 4, ventModifier: 0.8, boostModifier: 1.05 },
  { id: "twilight-surge", title: "Twilight Surge", ticker: "Twilight surge colors the chamber.", description: "Dim dimensional tides heave energy both ways.", volatility: 1.3, bias: 0.5, duration: 3, ventModifier: 1.05, boostModifier: 0.95 },
];

export const stratagemLibrary = [
  { id: "skyshield-dome", name: "Skyshield Dome", callSign: "Skyshield Seven", summary: "Drops a radiant barrier that hardens the evac zone against incoming fire.", difficulty: 0, sequence: ["up", "down", "left", "right"] },
  { id: "starfall-barrage", name: "Starfall Barrage", callSign: "Orbital Lance", summary: "Signals an orbital lance strike to vaporise entrenched hostiles.", difficulty: 0, sequence: ["right", "down", "down", "up"] },
  { id: "medevac-spire", name: "Medevac Spire", callSign: "Angel Flight", summary: "Deploys medevac drones that auto-extract injured allies.", difficulty: 0, sequence: ["down", "left", "up", "up"] },
  { id: "aegis-reservoir", name: "Aegis Reservoir", callSign: "Beacon Ward", summary: "Projects a regenerative field that empowers friendly abilities.", difficulty: 1, sequence: ["up", "up", "right", "down", "left"] },
  { id: "tempest-lancers", name: "Tempest Lancers", callSign: "Storm Team", summary: "Summons aerial lancers to sweep the battlefield.", difficulty: 1, sequence: ["left", "up", "right", "down", "down"] },
  { id: "quantum-net", name: "Quantum Net", callSign: "Nullwave", summary: "Deploys a net of nullwave pylons that snare teleporting foes.", difficulty: 1, sequence: ["down", "down", "left", "right", "up"] },
  { id: "sunforge-cannon", name: "Sunforge Cannon", callSign: "Solar Forge", summary: "Calibrates a solar cannon that burns a path through armour.", difficulty: 2, sequence: ["up", "right", "down", "left", "up", "right"] },
  { id: "phase-relay", name: "Phase Relay", callSign: "Blink Gate", summary: "Establishes a temporary blink gate for allied reinforcements.", difficulty: 2, sequence: ["right", "right", "up", "down", "left", "left"] },
  { id: "tidal-catalyst", name: "Tidal Catalyst", callSign: "Cascade Prime", summary: "Unleashes a gravity pulse that knocks back remaining threats.", difficulty: 2, sequence: ["left", "down", "down", "up", "right", "up"] },
  { id: "storm-halo", name: "Storm Halo", callSign: "Nimbus Guard", summary: "Erects a storm buffer that diffuses ballistic fire.", difficulty: 0, sequence: ["up", "up", "down", "right"] },
  { id: "orbital-warden", name: "Orbital Warden", callSign: "Sentinel Crown", summary: "Locks orbital defense satellites onto shared firing solutions.", difficulty: 1, sequence: ["right", "up", "left", "down", "right"] },
  { id: "shadow-veil", name: "Shadow Veil", callSign: "Night Whisper", summary: "Deploys holo-decoys to confuse tracking systems.", difficulty: 1, sequence: ["down", "right", "right", "up", "left"] },
  { id: "wildfire-aegis", name: "Wildfire Aegis", callSign: "Phoenix Watch", summary: "Ignites a perimeter ring that repels incoming waves.", difficulty: 2, sequence: ["up", "left", "down", "left", "right", "up"] },
  { id: "thunder-strike", name: "Thunder Strike", callSign: "Storm Herald", summary: "Calls down twin thunderbolts to stun armored units.", difficulty: 1, sequence: ["up", "right", "down", "right", "up"] },
  { id: "glacial-barrier", name: "Glacial Barrier", callSign: "Frost Crown", summary: "Summons cryo-crystals that slow hostile advances.", difficulty: 2, sequence: ["left", "left", "up", "down", "down", "right"] },
  { id: "phoenix-dive", name: "Phoenix Dive", callSign: "Ash Wing", summary: "Drops incendiary pods followed by restorative nanites.", difficulty: 2, sequence: ["up", "down", "up", "right", "right", "down"] },
  { id: "titan-barrage", name: "Titan Barrage", callSign: "Atlas Battery", summary: "Coordinates heavy artillery for a staggered saturation strike.", difficulty: 3, sequence: ["right", "down", "right", "up", "left", "up", "right"] },
  { id: "aurora-lance", name: "Aurora Lance", callSign: "Polar Ray", summary: "Fires a prismatic beam that disrupts shields.", difficulty: 2, sequence: ["up", "up", "left", "right", "down", "down"] },
  { id: "horizon-link", name: "Horizon Link", callSign: "Relay Echo", summary: "Connects distant squads through a hardened comm uplink.", difficulty: 1, sequence: ["left", "up", "up", "right", "down"] },
  { id: "echo-sweep", name: "Echo Sweep", callSign: "Specter Grid", summary: "Sweeps the field with sonic pulses that reveal cloaked foes.", difficulty: 0, sequence: ["down", "left", "right", "up"] },
  { id: "sentinel-wall", name: "Sentinel Wall", callSign: "Bulwark Line", summary: "Raises interlocking hard-light barricades.", difficulty: 1, sequence: ["right", "left", "up", "up", "down"] },
  { id: "manticore-sting", name: "Manticore Sting", callSign: "Stingray", summary: "Launches guided micromissiles that track evasive targets.", difficulty: 2, sequence: ["down", "right", "up", "left", "down", "right"] },
  { id: "comet-rain", name: "Comet Rain", callSign: "Falling Star", summary: "Coordinates a sequenced meteor barrage across the frontline.", difficulty: 2, sequence: ["up", "right", "right", "down", "down", "left"] },
  { id: "zero-hour", name: "Zero Hour", callSign: "Final Light", summary: "Triggers emergency bunkers and pulls squads to safety.", difficulty: 3, sequence: ["left", "up", "right", "up", "left", "down", "down"] },
  { id: "nova-hammer", name: "Nova Hammer", callSign: "Solar Anvil", summary: "Channels a solar flare into a focused ground strike.", difficulty: 2, sequence: ["right", "up", "right", "down", "left", "left"] },
  { id: "prism-field", name: "Prism Field", callSign: "Refraction", summary: "Splits incoming energy into harmless spectra.", difficulty: 1, sequence: ["up", "left", "down", "right", "up"] },
  { id: "cyclone-guard", name: "Cyclone Guard", callSign: "Gale Shield", summary: "Whips a defensive cyclone to deflect projectiles.", difficulty: 2, sequence: ["down", "down", "right", "up", "left", "up"] },
  { id: "nightfall-shroud", name: "Nightfall Shroud", callSign: "Blackout", summary: "Casts a shadow grid that blinds hostile targeting systems.", difficulty: 1, sequence: ["left", "down", "left", "up", "right"] },
  { id: "chrono-beacon", name: "Chrono Beacon", callSign: "Timekeeper", summary: "Stretches local time to give allies rapid redeploys.", difficulty: 2, sequence: ["up", "up", "right", "right", "down", "left"] },
  { id: "inferno-salve", name: "Inferno Salve", callSign: "Cinder Squad", summary: "Combines flame suppressants with adrenaline boosters.", difficulty: 2, sequence: ["down", "right", "down", "right", "up", "up"] },
  { id: "mirage-drift", name: "Mirage Drift", callSign: "Illusion Wing", summary: "Deploys holographic squads to draw enemy fire.", difficulty: 1, sequence: ["right", "up", "up", "left", "left"] },
  { id: "siege-breaker", name: "Siege Breaker", callSign: "Iron Rain", summary: "Coordinated breaching charges punch through fortified lines.", difficulty: 3, sequence: ["up", "right", "down", "right", "up", "left", "down"] },
  { id: "gaia-bulwark", name: "Gaia Bulwark", callSign: "Earth Ward", summary: "Raises earthen ramparts to cover the advance.", difficulty: 1, sequence: ["left", "up", "down", "down", "right"] },
  { id: "thunder-charge", name: "Thunder Charge", callSign: "Bolt Squadron", summary: "Electrifies spearhead units for a shock assault.", difficulty: 2, sequence: ["up", "right", "up", "down", "right", "down"] },
  { id: "radiant-bridge", name: "Radiant Bridge", callSign: "Beacon Path", summary: "Creates a photonic bridge over hazardous terrain.", difficulty: 1, sequence: ["right", "up", "left", "left", "down"] },
  { id: "glimmer-veil", name: "Glimmer Veil", callSign: "Dazzle", summary: "Cascades glittering chaff to foul targeting optics.", difficulty: 0, sequence: ["up", "left", "right", "right"] },
  { id: "frost-rampart", name: "Frost Rampart", callSign: "Glacier Wing", summary: "Builds crystalline barriers that slow enemy advances.", difficulty: 2, sequence: ["left", "left", "down", "up", "right", "up"] },
  { id: "striker-spear", name: "Striker Spear", callSign: "Javelin", summary: "Marks priority targets for precision strikes.", difficulty: 2, sequence: ["up", "right", "right", "up", "down", "left"] },
  { id: "guardian-angel", name: "Guardian Angel", callSign: "Halo", summary: "Drops defensive drones that intercept incoming fire.", difficulty: 1, sequence: ["down", "up", "right", "up", "left"] },
  { id: "cyclone-arrow", name: "Cyclone Arrow", callSign: "Tempest Tip", summary: "Launches a spiralling payload that clears entrenched nests.", difficulty: 2, sequence: ["right", "down", "left", "down", "right", "up"] },
  { id: "lode-star", name: "Lode Star", callSign: "Compass", summary: "Magnetises armor plating to deflect kinetic rounds.", difficulty: 1, sequence: ["up", "up", "left", "down", "left"] },
  { id: "iron-sky", name: "Iron Sky", callSign: "Aegis Flight", summary: "Summons interceptor wings to screen the battlefield.", difficulty: 2, sequence: ["right", "right", "down", "left", "up", "up"] },
  { id: "ember-fury", name: "Ember Fury", callSign: "Pyre", summary: "Detonates incendiary mines across the frontline.", difficulty: 2, sequence: ["up", "down", "right", "right", "down", "left"] },
  { id: "arc-flash", name: "Arc Flash", callSign: "Volt Blade", summary: "Channels cutting arcs through heavy armor.", difficulty: 1, sequence: ["right", "down", "up", "up", "left"] },
  { id: "bastion-seal", name: "Bastion Seal", callSign: "Fortress", summary: "Locks breach points with quick-setting barrier foam.", difficulty: 2, sequence: ["left", "right", "down", "down", "up", "right"] },
  { id: "tempest-wall", name: "Tempest Wall", callSign: "Gale Guard", summary: "Spins hurricane-force winds to redirect artillery.", difficulty: 3, sequence: ["up", "left", "up", "right", "down", "right", "up"] },
  { id: "pulse-lifter", name: "Pulse Lifter", callSign: "Skyhook", summary: "Gravitic lifters hoist squads out of danger zones.", difficulty: 1, sequence: ["down", "left", "up", "up", "right"] },
  { id: "helix-strike", name: "Helix Strike", callSign: "Spiral", summary: "Launches a spiralling bombardment that threads around cover.", difficulty: 3, sequence: ["right", "up", "right", "down", "left", "down", "right"] },
  { id: "phalanx-protocol", name: "Phalanx Protocol", callSign: "Shield Line", summary: "Locks units into a rotating shield formation.", difficulty: 2, sequence: ["up", "up", "down", "left", "right", "right"] },
  { id: "nebula-shroud", name: "Nebula Shroud", callSign: "Cosmic Veil", summary: "Floods the zone with ionised mist to hide allied maneuvers.", difficulty: 2, sequence: ["left", "right", "up", "up", "down", "left"] },
];

export const techLockpickLibrary = {
  standard: {
    length: 5,
    options: 8,
    words: [
      "NEXUS", "SIGMA", "PROBE", "TRACE", "PLASM", "ARRAY", "IONIC", "PIXEL", "NODES", "LASER",
      "FIBER", "CIRCU", "GRIDS", "LOGIC", "VAULT", "PHASE", "RADAR", "CRYPT", "GAMMA", "RADIX",
      "FUSOR", "AURIC", "QUILL", "BLADE", "FOCUS", "VISTA", "LUMEN", "PULSE", "QUARK", "HELIX",
      "LYRIC", "SYNTH", "COREX", "METAL", "ROTOR", "STACK", "SIGIL", "EMBER", "FORGE", "SABLE",
      "RALLY", "SPARK", "ETHER", "FRAME", "MIRAI", "IONIX", "RELAY", "CRANE", "SHIFT", "TEMPO",
    ],
  },
  advanced: {
    length: 6,
    options: 10,
    words: [
      "PHOTON", "CRYPTO", "VECTOR", "NEURAL", "MODULE", "QUANTA", "SCRYER", "PULSER", "SYSTEM", "TERMIN",
      "CORTEX", "RIGGED", "SPIRAL", "SHADOW", "WIZARD", "FORGED", "LATTIC", "THREAD", "OUTPUT", "FUSION",
      "SIGNAL", "ENERGY", "VAULTS", "NOVAST", "BINARY", "MATRIX", "FISSION", "DRIVER", "THRUST", "INFORM",
      "BUFFER", "SCALAR", "VORTEX", "CIPHER", "ORACLE", "NIMBUS", "TETHER", "SWITCH", "CIRRUS", "MAGNET",
      "DOMAIN", "CLIENT", "SERVER", "PACKET", "PROTON", "NEBULA", "SPECTR", "GALVAN", "UPLINK", "RADIAL",
    ],
  },
  exotic: {
    length: 6,
    options: 12,
    words: [
      "AETHER", "OVERDR", "PRISMZ", "CYGNUS", "QUARKS", "ENTROP", "CHIMER", "OBELIS", "MANTIS", "VIOLET",
      "LUMINA", "SINGUL", "CRYPTX", "ZEPHIR", "ASTRAL", "MYTHOS", "ZENITH", "PHOENX", "VORTAL", "ECHOIR",
      "SPHINX", "TANTRA", "RELIQU", "AURORA", "COSMOS", "OMENIC", "MIRROR", "ALCHEM", "SERAPH", "RUNEAX",
      "ETHERY", "HEXATE", "DRAGON", "VALKYR", "LAGRAN", "SOLACE", "ZEPHYR", "RADIUM", "ARCANE", "LUXION",
      "OBLIVI", "STELLA", "FAELYN", "ASTRYX", "CHRONO", "SPIRYX", "WYRMIC", "LUCENT", "SHARDS", "OMEGAX",
    ],
  },
};
