// Shared DM PIN hash used for authentication and character protection. The
// metadata below is generated by `tools/generate-dm-pin.js` during the build
// pipeline so the plaintext PIN never ships with the bundle.
export const DM_PIN = {
  hash: 'jnHUUj/vztK449EzTlSMvsFdIrvw24roOEo3g0i01Ls=',
  salt: 'yszLuHwFAXA5MuSscO+9vQ==',
  iterations: 120000,
  keyLength: 32,
  digest: 'SHA-256',
};

