// Shared DM PIN hash used for authentication and character protection. The
// metadata below is generated by `tools/generate-dm-pin.js` during the build
// pipeline so the plaintext PIN never ships with the bundle.
export const DM_PIN = {
  hash: 'jnHUUj/vztK449EzTlSMvsFdIrvw24roOEo3g0i01Ls=',
  salt: 'yszLuHwFAXA5MuSscO+9vQ==',
  iterations: 120000,
  keyLength: 32,
  digest: 'SHA-256',
};

// Optional device fingerprint used to hide DM tools on unauthorized devices.
// Leave this empty to allow any device with the DM PIN to see the tools.
// To restrict the tools to a single device, compute the fingerprint using
// `window.computeDmDeviceFingerprint()` in the browser console and copy the
// resulting string here.
export const DM_DEVICE_FINGERPRINT = '';
