// Lighthearted reminders to amuse players and hint at game mechanics.
// Tips are served in a random order without repeats until all have been shown.
const tips = [
  'A hero is just one good roll away.',
  'Check your gear before heading out!',
  'Remember to take breaks between battles.',
  'Allies can turn the tide—track your faction rep.',
  'Saving your progress is the real treasure.',
  'Try a new build; surprises keep enemies guessing.',
  'Even mutants need snacks; pack some supplies.',
  'Roll high and stay hydrated.',
  'Keep an eye on initiative—speed wins fights.',
  'Spare dice make great improvised weapons.',
  'A well-timed joke can heal the party.',
  'Always ask what\'s behind the mysterious door.',
  'Critical fails build character.',
  'Spell check your spells.',
  'When in doubt, duck.',
  'Inventory space is precious—pack wisely.',
  'Maps are your friend; doodle freely.',
  'Never split the party... unless it\'s hilarious.',
  'Cats in dungeons are always suspicious.',
  'A shiny treasure may be a shiny trap.',
  'Keep your story journal up to date.',
  'Random encounters are the spice of adventure.',
  'Charisma can open doors brute force cannot.',
  'Befriend the NPC with snacks.',
  'Always note the time of day—sunsets hide surprises.',
  'Glowing mushrooms are rarely edible.',
  'Fear the quiet goblin.',
  'Read the rules, then bend them creatively.',
  'Teamwork makes the critical hits crit harder.',
  'Practice your victory dance.',
  'A humble healer saves the day.',
  'Stealth is just loudness measured differently.',
  'Loot responsibly; respect property rights.',
  'Do not taunt the dragon.',
  'Invisible ink reveals invisible clues.',
  'Trade jokes with trolls; they love wordplay.',
  'A clean sword cuts deeper.',
  'Keep track of the moon; werewolves do.',
  'Fire solves puzzles; water solves fire.',
  'Check for traps before you leap.',
  'Rations taste better after a win.',
  'Laugh in the face of danger, then run.',
  'Let the bard sing; it boosts morale.',
  'An organized inventory saves lives.',
  'Pick a signature catchphrase early.',
  'Use objects creatively; a spoon is a tool.',
  'Always knock before entering haunted houses.',
  'Carry chalk for sketchy situations.',
  'Don\'t lick the mysterious crystal.',
  'Spare rope is always useful.',
  'Friends who bring healing potions are true friends.',
  'The best treasure is the memories made.',
  'A shield on the back is still a shield.',
  'Goblins appreciate fan art.',
  'Remember: stealth checks apply to crunchy snacks.',
  'Don\'t feed the mimic.',
  'Every riddle has a punny answer.',
  'A tidy camp makes for rested heroes.',
  'Shiny armor attracts shiny foes.',
  'Always let the rogue go first.',
  'Witty banter earns experience points.',
  'A torch doubles as a fashion statement.',
  'Dragon hoards are great places for selfies.',
  'Keep your dice on their best behavior.',
  'Wear comfortable boots; journeys are long.',
  'Champion naps between skirmishes.',
  'Don\'t cross streams of magic.',
  'Whisper to animals; they might whisper back.',
  'Never underestimate a well-timed distraction.',
  'Remember to celebrate small victories.',
  'A lucky charm never hurts.',
  'Snails are nature\'s way of teaching patience.',
  'Every hero needs a theme song.',
  'Always rehearse your dramatic entrances.',
  'Don\'t anger the village chickens.',
  'A humble grin disarms more than swords.',
  'Mystery potions are a roll of the dice.',
  'Keep your story journal waterproof.',
  'Never refuse a side quest; adventure awaits.',
  'Always check for secret passageways.',
  'Sing to your gear; it might level up.',
  'Dodge rolls make excellent dance moves.',
  'A balanced diet includes victory and pie.',
  'Wizards love libraries; befriend librarians.',
  'Use your environment; walls are just big shields.',
  'Never loan your only weapon.',
  'A friendly wave can stop a battle.',
  'Trust your instincts—and your party.',
  'Remember the rules of magic etiquette.',
  'Take notes on enemy weaknesses.',
  'Don\'t forget to level up your pet.',
  'A quiet forest is a suspicious forest.',
  'Treasure maps don\'t fold themselves.',
  'Beware of singing fish.',
  'Make friends with the shopkeeper.',
  'Always identify the potion before drinking.',
  'Keep an emergency snack pouch.',
  'A campfire tale boosts resolve.',
  'The weather can be an ally.',
  'Practice your heroic pose.',
  'Never trust a smiling skull.',
  'Wear a helmet; dragons bite.',
  'Always have an escape plan.',
  'Collect strange keys; doors appear.',
  'Read the fine print on magical contracts.',
  'Spending gold is half the fun.',
  'Ask the NPCs about their dreams.',
  'You can never have too many pockets.',
  'A party that laughs together lasts together.',
  'Use mirrors to look around corners.',
  'Remember to update your map markers.',
  'Sometimes, retreat is the boldest move.',
  'Check the sky for airships.',
  'Don\'t forget the festival calendar.',
  'A well-placed sneeze can spoil stealth.',
  'Be kind to wandering merchants.',
  'Keep a quill handy for autograph seekers.',
  'Star charts may reveal secret paths.',
  'Collect souvenirs from each town.',
  'Every scar tells a story; wear them proudly.',
  'Gratitude grants invisible buffs.',
  'Study your enemy\'s footwear; clues lie beneath.',
  'Dried herbs make wonderful bookmarks.',
  'Light travels faster than sound; scout with it.',
  'Offer dragons tea; they may appreciate civility.',
  'Practice juggling to improve dexterity.',
  'Shout your spell names for extra flair.',
  'Always check the expiration date on potions.',
  'Keep a diary; future bards will thank you.',
  'A friendly rivalry spices up training.',
  'Be wary of chests that purr.',
  'Celebrate crits with confetti.',
  'Carry a spare pair of socks.',
  'Never say "what could go wrong?" aloud.',
  'Hold on to that cursed ring—it might be useful.',
  'Don\'t forget to look behind you.',
  'Smell the flowers, but avoid the carnivorous ones.',
  'Ask old sages about their hobbies.',
  'A group handshake boosts morale.',
  'Practice subtlety in loud armor.',
  'Always search the ceiling for clues.',
  'Learn a few words of every language.',
  'Doodles in the margins spark inspiration.',
  'Breathe deeply before the boss battle.',
  'A cautious friend is a lasting friend.',
  'You never know when a spoon saves the day.',
  'Curiosity created the best side quests.',
  'Thank your healer after every adventure.',
  'High fives after every victory.',
  'Even villains appreciate fan mail.',
  'Carry a small bell for dramatic reveals.',
  'Every bridge has a story; listen before crossing.',
  'Don\'t leave home without a towel.',
  'Respect ancient ruins; they have feelings.',
  'Collect small rocks for negotiating with trolls.',
  'Keep a list of noble deeds for bragging rights.',
  'Always stretch before casting lightning.',
  'Label your potions with funny names.',
  'Practice stealth on squeaky floors.',
  'Never underestimate a well-timed nap.',
  'Compliment a giant on their footwear.',
  'Random tables are the universe\'s dice.',
  'Pack extra ink for your quill.',
  'Celebrate new levels with cake.',
  'Look for patterns in the stars.',
  'Train your mount to respond to secret whistles.',
  'Remember the names of the tavern dogs.',
  'A well-thrown pebble can change history.',
  'Decorate your shield; art intimidates foes.',
  'Always leave a thank-you note for quest givers.',
  'Keep your spellbook organized by color.',
  'Mysterious doors love polite knocks.',
  'Carry a harmonica for surprise jams.',
  'Watch out for enchanted furniture.',
  'The quietest NPCs have the loudest secrets.',
  'Count your steps—it may reveal hidden passages.',
  'Singing in dungeons echoes morale.',
  'Treat your mounts like royalty.',
  'Carry seeds to plant after battles.',
  'Write fan fiction about your party.',
  'Never refuse free maps.',
  'Wear bright colors in gloomy caves.',
  'Plan your victory speech in advance.',
  'Start every quest with a smile.',
  'A good pun can disarm foes.',
  'Remember, even dragons have hobbies.',
  'Friendship bracelets are powerful artifacts.',
  'Mages love organized scrolls.',
  'Let goblins tell jokes; they need the practice.',
  'Practice your autograph for future fame.',
  'Always carry a spare lockpick.',
  'Grease spells double as cooking aids.',
  'Keep your helmet on during arguments.',
  'Find joy in every dice roll.',
  'Let the map guide your imagination.',
  'Talk to statues; some enjoy company.',
  'Beware of suspiciously helpful imps.',
  'Carry a whistle for dramatic pauses.',
  'Summon courage with a favorite tune.',
  'End every session with a cliffhanger.',
];

let queue = [];

function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

export function getNextTip() {
  if (queue.length === 0) {
    queue = shuffle([...tips]);
  }
  return queue.pop();
}

export { tips };
