// Lighthearted reminders to amuse players and hint at game mechanics.
// Tips are served in a random order without repeats until all have been shown.
const tips = [
  `1. Do not attempt to catch falling civilians with your face.`,
  `2. Collateral damage is not a trophy. Stop keeping score.`,
  `3. If you can't lift it safely, don't. We'll bill you for the street repairs.`,
  `4. Speedsters: traffic laws still apply. Especially red lights.`,
  `5. Always check your cape length near escalators. Trust us.`,
  `6. "Improvised weapon" does not mean "use the nearest bus."`,
  `7. Saving the cat from the tree is noble. Throwing the tree is not.`,
  `8. Heroes who monologue often miss explosions.`,
  `9. When in doubt, evacuate civilians. They complain less than craters.`,
  `10. Your powers do not make you fireproof. That's called hubris.`,
  `11. Mind readers: no, we don't want your dating advice.`,
  `12. Don't punch dimensional rifts. That never ends well.`,
  `13. Never shout your signature move louder than the actual explosion.`,
  `14. Stop naming every gadget after yourself. O.M.N.I. owns it anyway.`,
  `15. If your plan involves "winging it," civilians will also be winging it.`,
  `16. Teleporters: always confirm coordinates. We are still missing an agent.`,
  `17. Energy manipulators: city grids are not snacks.`,
  `18. The phrase "I meant to do that" is not an acceptable incident report.`,
  `19. Heroes who fly low create wind damage. Pay attention to umbrellas.`,
  `20. Illusionists: stop photobombing news broadcasts.`,
  `21. No matter how fast you are, bullets still outrun arrogance.`,
  `22. Civilians first. Property second. Your ego never.`,
  `23. If your solution involves more explosions, it's not a solution.`,
  `24. Don't put civilians "somewhere safe" without telling anyone where that is.`,
  `25. Do not throw villains into orbit. We don't track satellites for fun.`,
  `26. Shapeshifters: please return to your original form for ID checks.`,
  `27. Never announce your weaknesses. Villains are paying attention.`,
  `28. Yes, the skyscraper looks sturdy. No, don't test it.`,
  `29. Heroes who whisper one-liners mid-rescue creep people out.`,
  `30. The media is watching. So are we. Act accordingly.`,
  `31. Telekinetics: glass panes are not frisbees.`,
  `32. Catching a car is only useful if you put it down gently.`,
  `33. Heroes who fight underwater tend to drown. Stop trying.`,
  `34. Fire users: hydrants are allies, not targets.`,
  `35. Never trade insults with villains. They're better at it.`,
  `36. A hostage situation is not karaoke night.`,
  `37. Do not attempt to "out-drama" Morvox. You'll lose.`,
  `38. Civilians don't care if you glow. They care if they're safe.`,
  `39. Always check for civilians before collapsing a bridge "strategically."`,
  `40. Heroes who use catchphrases should rehearse them first.`,
  `41. Energy blasts and gas stations are a poor combination.`,
  `42. "Collateral damage" is not a heroic synonym for "oops."`,
  `43. Civilians don't need to know how cool your powers look.`,
  `44. Never use your team as human projectiles.`,
  `45. Flying into thunderstorms is not bravery. It's suicide.`,
  `46. Heroes who improvise plans must improvise cleanup.`,
  `47. Remember: the news always arrives before the help does.`,
  `48. Mind control is not flirting.`,
  `49. Civilians panic when you glow ominously. Smile instead.`,
  `50. Stop signing autographs during active fires.`,
  `51. Yes, your powers can break the sound barrier. Stop proving it downtown.`,
  `52. If your teammate yells "duck," duck.`,
  `53. Shouting "I got this" is statistically followed by hospital visits.`,
  `54. Do not attempt to suplex a kaiju.`,
  `55. Civilians rarely appreciate being "teleported somewhere fun."`,
  `56. Heroes who stop for selfies mid-battle don't live long.`,
  `57. Villains monologue because you let them. Fix that.`,
  `58. The phrase "hold my beer" is forbidden in O.M.N.I. operations.`,
  `59. Heroes who glow in the dark should not sneak.`,
  `60. Stop calling HQ asking if sharks count as "hostile combatants."`,
  `61. Civilians do not enjoy sudden flight demonstrations.`,
  `62. Heroics require planning. Improvised chaos is villain work.`,
  `63. Never eat glowing shards. They are not candy.`,
  `64. Illusions of fire alarms cause more panic than fires.`,
  `65. Heroes who punch tanks usually become street art.`,
  `66. "Distracting the villain" doesn't mean stand still and yell.`,
  `67. Stop recruiting interns. That's our job.`,
  `68. Civilians expect rescues, not theatrics.`,
  `69. O.M.N.I. monitors your comms. Stop singing.`,
  `70. Heroes who ignore backup requests become funerals.`,
  `71. Firefighters hate when you improvise. Listen to them.`,
  `72. Civilians remember what you break more than what you save.`,
  `73. If you can't solve it, stall it until smarter heroes arrive.`,
  `74. Don't test gravity mid-mission. It always wins.`,
  `75. Heroes who fight shirtless increase casualty risk.`,
  `76. Never drop a villain "just a little."`,
  `77. Civilians don't need speeches. They need exits.`,
  `78. Heroes who underestimate Greyline contracts vanish quickly.`,
  `79. Stop renaming your powers every mission.`,
  `80. Do not attempt to "out-meme" the internet. You'll lose.`,
  `81. Heroes who jump off buildings must know how to land.`,
  `82. A dramatic pause is not worth a burning bus.`,
  `83. Civilians don't care about your tier rank. They care about their kids.`,
  `84. Never joke about radiation. Ever.`,
  `85. Heroes who hoard loot are demoted to cleanup crew.`,
  `86. Don't point lasers at the news chopper.`,
  `87. Always check for invisible enemies. Or don't and die.`,
  `88. Heroes who underestimate O.M.N.I. rules don't stay heroes.`,
  `89. Never throw allies without consent.`,
  `90. If you say "I'll handle this alone," you won't.`,
  `91. Civilians don't like being "tested."`,
  `92. Heroes who eat on duty get food poisoning on duty.`,
  `93. Never assume the villain is done talking. Shoot first.`,
  `94. Stop asking if kaiju bleed.`,
  `95. Heroes who argue mid-fight make villains stronger.`,
  `96. Do not attempt to teach villains morality during combat.`,
  `97. Always expect cameras. Even in the bathroom.`,
  `98. Heroes who joke about paperwork will get more paperwork.`,
  `99. Collateral damage makes headlines. So do you. Choose wisely.`,
  `100. O.M.N.I. is always watching. Especially you.`,
];

let queue = [];

function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

export function getNextTip() {
  if (queue.length === 0) {
    queue = shuffle([...tips]);
  }
  return queue.pop();
}

export { tips };
