/* eslint-disable */
// This file is generated by tools/build-levels.mjs
export const LEVELS = [
  {
    "level": 1,
    "tierNumber": 5,
    "tierLabel": "Tier 5 – Rookie",
    "subTier": "A",
    "xp": 0,
    "proficiencyBonus": 2,
    "gains": "Character creation"
  },
  {
    "level": 2,
    "tierNumber": 5,
    "tierLabel": "Tier 5 – Rookie",
    "subTier": "B",
    "xp": 300,
    "proficiencyBonus": 2,
    "gains": "+5 HP and Power Evolution"
  },
  {
    "level": 3,
    "tierNumber": 5,
    "tierLabel": "Tier 5 – Rookie",
    "subTier": "C",
    "xp": 900,
    "proficiencyBonus": 2,
    "gains": "Augment 1"
  },
  {
    "level": 4,
    "tierNumber": 5,
    "tierLabel": "Tier 4 Begins (+1 Stat)",
    "subTier": "D",
    "xp": 2700,
    "proficiencyBonus": 2,
    "gains": "Signature Move Evolution and +1 SP Max"
  },
  {
    "level": 5,
    "tierNumber": 4,
    "tierLabel": "Tier 4 Begins (+1 Stat)",
    "subTier": "A",
    "xp": 6500,
    "proficiencyBonus": 3,
    "gains": "+5 HP and Power Evolution"
  },
  {
    "level": 6,
    "tierNumber": 4,
    "tierLabel": "Tier 4 Begins (+1 Stat)",
    "subTier": "B",
    "xp": 14000,
    "proficiencyBonus": 3,
    "gains": "Augment 2"
  },
  {
    "level": 7,
    "tierNumber": 4,
    "tierLabel": "Tier 4 Begins (+1 Stat)",
    "subTier": "C",
    "xp": 23000,
    "proficiencyBonus": 3,
    "gains": "+1 SP Max and Power Evolution"
  },
  {
    "level": 8,
    "tierNumber": 4,
    "tierLabel": "Tier 3 Begins (+1 Stat)",
    "subTier": "D",
    "xp": 34000,
    "proficiencyBonus": 3,
    "gains": "Power or Signature Move Evolution"
  },
  {
    "level": 9,
    "tierNumber": 3,
    "tierLabel": "Tier 3 Begins (+1 Stat)",
    "subTier": "A",
    "xp": 48000,
    "proficiencyBonus": 4,
    "gains": "Augment 3"
  },
  {
    "level": 10,
    "tierNumber": 3,
    "tierLabel": "Tier 3 Begins (+1 Stat)",
    "subTier": "B",
    "xp": 64000,
    "proficiencyBonus": 4,
    "gains": "+5 HP and Power Evolution"
  },
  {
    "level": 11,
    "tierNumber": 3,
    "tierLabel": "Tier 3 Begins (+1 Stat)",
    "subTier": "C",
    "xp": 85000,
    "proficiencyBonus": 4,
    "gains": "+1 SP Max"
  },
  {
    "level": 12,
    "tierNumber": 3,
    "tierLabel": "Tier 2 Begins (+1 Stat &)",
    "subTier": "D",
    "xp": 100000,
    "proficiencyBonus": 4,
    "gains": "Augment 4"
  },
  {
    "level": 13,
    "tierNumber": 2,
    "tierLabel": "Tier 2 Begins (+1 Stat &)",
    "subTier": "A",
    "xp": 120000,
    "proficiencyBonus": 5,
    "gains": "+5 HP and Power Evolution"
  },
  {
    "level": 14,
    "tierNumber": 2,
    "tierLabel": "Tier 2 Begins (+1 Stat &)",
    "subTier": "B",
    "xp": 140000,
    "proficiencyBonus": 5,
    "gains": "+1 SP Max"
  },
  {
    "level": 15,
    "tierNumber": 2,
    "tierLabel": "Tier 2 Begins (+1 Stat &)",
    "subTier": "C",
    "xp": 165000,
    "proficiencyBonus": 5,
    "gains": "Augment 5"
  },
  {
    "level": 16,
    "tierNumber": 2,
    "tierLabel": "Tier 1 Begins (+1 Stat)",
    "subTier": "D",
    "xp": 195000,
    "proficiencyBonus": 5,
    "gains": "Legendary Gear Access"
  },
  {
    "level": 17,
    "tierNumber": 1,
    "tierLabel": "Tier 1 Begins (+1 Stat)",
    "subTier": "A",
    "xp": 225000,
    "proficiencyBonus": 6,
    "gains": "+5 HP and Power Evolution"
  },
  {
    "level": 18,
    "tierNumber": 1,
    "tierLabel": "Tier 1 Begins (+1 Stat)",
    "subTier": "B",
    "xp": 265000,
    "proficiencyBonus": 6,
    "gains": "+1 SP Max"
  },
  {
    "level": 19,
    "tierNumber": 1,
    "tierLabel": "Tier 1 Begins (+1 Stat)",
    "subTier": "C",
    "xp": 305000,
    "proficiencyBonus": 6,
    "gains": "Augment 6"
  },
  {
    "level": 20,
    "tierNumber": 0,
    "tierLabel": "Ascendant Tier (+1 Stat)",
    "subTier": "D (Ω)**",
    "xp": 355000,
    "proficiencyBonus": 7,
    "gains": "Transcendent Trait"
  }
];
